yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """Модель сообщества."""
    title = models.CharField(max_length=200)
    slug = models.SlugField(
        unique=True,
        db_index=True,
        verbose_name='URL'
    )
    description = models.TextField()

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    """Модель публикаций."""
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    """Модель комментариев."""
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self) -> str:
        return self.post


class Follow(models.Model):
    """Модель подписок на авторов."""
    user = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL,
        related_name='following'
    )

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow'
            )
        ]

    def __str__(self) -> str:
        return f' Пользователь {self.user} подписан на {self.authors}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    """Форма для создания и редактирования постов."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['group'].empty_label = 'Группа не выбрана'

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': 'Текст', 'group': 'Группа'}
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост'
        }


class CommentForm(forms.ModelForm):
    """Форма для добавления комментариев постов."""
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Follow, Group, Post, User
from .forms import PostForm, CommentForm
from core.paginator_custome import paginator_for_posts
from yatube.settings import NUM_POSTS_PER_PAGE


def index(request):
    """Вывод последних 10 публикаций на главную страницу."""
    post_list = Post.objects.all().select_related('group')
    page_obj = paginator_for_posts(
        request,
        post_list,
        NUM_POSTS_PER_PAGE
    )
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Вывод последних 10 публикаций сообщества."""
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = paginator_for_posts(
        request,
        post_list,
        NUM_POSTS_PER_PAGE
    )
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """Страница профиля автора."""
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = paginator_for_posts(
        request,
        post_list,
        NUM_POSTS_PER_PAGE
    )
    template = 'posts/profile.html'
    context = {
        'page_obj': page_obj,
        'author': author,
    }
    if request.user.is_authenticated and request.user != username:
        following = author.following.filter(user=request.user)
        context['following'] = following
    return render(request, template, context)


def post_detail(request, post_id):
    """Страница деталей поста."""
    post_user = get_object_or_404(Post, id=post_id)
    total_posts = post_user.author.posts.count()
    form = CommentForm()
    comments = post_user.comments.all()
    template = 'posts/post_detail.html'
    context = {
        'post_user': post_user,
        'total_posts': total_posts,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """Страница для создания поста."""
    author = request.user
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = author
        post.save()
        return redirect('posts:profile', author)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """Страница для редактирования поста."""
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post.pk)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.pk)
    return render(
        request,
        'posts/create_post.html',
        {'form': form, 'is_edit': True}
    )


@login_required
def add_comment(request, post_id):
    """Добавление комментария к посту."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id)


@login_required
def follow_index(request):
    """Страница авторов,
    на которых подписан пользователь.
    """
    post_list = Post.objects.filter(
        author__following__user=request.user).select_related('group')
    page_obj = paginator_for_posts(
        request,
        post_list,
        NUM_POSTS_PER_PAGE
    )
    context = {
        'page_obj': page_obj,
    }
    template = 'posts/follow.html'
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Подписка на автора."""
    following = get_object_or_404(User, username=username)
    if following != request.user:
        Follow.objects.get_or_create(user=request.user, author=following)
        return redirect('posts:follow_index')
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """Отписаться от автора."""
    following = get_object_or_404(User, username=username)
    subscription = get_object_or_404(
        Follow, user=request.user, author=following
    )
    subscription.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}Новый пост{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}
          </div>
          <div class="card-body">
          {% load user_filters %}
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
              {% endfor %}
            {% endif %}
              <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="{{ form.text.id_for_label }}">
                  {{ form.text.label }}
                    {% if form.text.field.required %}                  
                      <span class="required text-danger" >*</span>
                    {% endif %}                  
                </label>

                  {{ form.text|addclass:'form-control' }}
              
                <small id="{{ form.text.id_for_label }}" class="form-text text-muted">
                  {{ form.text.help_text }}
                </small>                  
              </div>            
              <div class="form-group row my-3 p-3">
                <label for="{{ form.group.field.id_for_label }}">
                  {{ form.group.label }}
                    {% if form.group.field.required %}
                      <span class="required text-danger" >*</span>
                    {% endif %}
                </label>
                {{ form.group|addclass:'form-control' }}
                {% if form.group.field.help_text %}
                  <small id="{{ form.group.id_for_label }}" class="form-text text-muted">
                    {{ form.group.help_text }}
                  </small>
                {% endif %}
              </div>
              <div class="form-group row my-3 p-3">
                <label for="{{ form.image.field.id_for_label }}">
                  {{ form.image.label }}
                    {% if form.group.field.required %}
                      <span class="required text-danger" >*</span>
                    {% endif %}
                </label>
                {{ form.image|addclass:'form-control' }}
                {% if form.image.field.help_text %}
                  <small id="{{ form.image.id_for_label }}" class="form-text text-muted">
                    {{ form.image.help_text }}
                  </small>
                {% endif %}
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Подписка{% endblock %}
{% block content %}
{% load thumbnail %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        {% if page_obj %}     
          <h1>Избранные авторы</h1>
        {% else %}
          <h1>Вы пока не подписались ни на одного автора</h1>
        {% endif %}
          {% include 'posts/includes/switcher.html' %}
          {% for post in page_obj %}
            <article>
              <ul>
                <li>
                  Автор: {{ post.author.get_full_name }}
                  <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul>
              {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}      
              <p>
                {{ post.text }}
              </p>
              <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
            </article>
              {% if post.group.slug %}
                <a 
                  href="{% url 'posts:group_list' post.group.slug %}"
                >все записи группы</a>
              {% endif %}
              {% if not forloop.last %}<hr>{% endif %}  
          {% endfor %}
        {% include 'posts/includes/paginator.html' %}
        <!-- под последним постом нет линии -->
      </div>  
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества: {{ group.title }}{% endblock %}
{% block content %}
{% load thumbnail %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>{{ group.title }}</h1>
        <p>
          {{ group.description }}
        </p>
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author %}"
                >
                  все посты пользователя
                </a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}       
            <p>
              {{ post.text }}
            </p>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
          </article>
            {% if post.group.slug %}
              <a 
                href="{% url 'posts:group_list' post.group.slug %}"
              >все записи группы</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}         
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
        <!-- под последним постом нет линии -->
      </div>  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
{% load thumbnail %}
{% load cache %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <h1>Последние обновления на сайте</h1>
        {% cache 20 index_page %}
          {% include 'posts/includes/switcher.html' %}
          {% for post in page_obj %}
            <article>
              <ul>
                <li>
                  Автор: {{ post.author.get_full_name }}
                  <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul>
              {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}      
              <p>
                {{ post.text }}
              </p>
              <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
            </article>
              {% if post.group.slug %}
                <a 
                  href="{% url 'posts:group_list' post.group.slug %}"
                >все записи группы</a>
              {% endif %}
              {% if not forloop.last %}<hr>{% endif %}  
          {% endfor %}
        {% endcache %}
        {% include 'posts/includes/paginator.html' %}
        <!-- под последним постом нет линии -->
      </div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост{{ post_user.text|truncatechars:30 }}{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post_user.pub_date|date:"d E Y" }} 
        </li>
        <!-- если у поста есть группа -->
          {% if post_user.group.slug %}   
            <li class="list-group-item">
              Группа: {{ post_user.group }}
              <a href="{% url 'posts:group_list' post_user.group.slug %}">
                все записи группы
              </a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post_user.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ total_posts }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post_user.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post_user.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post_user.text }}
      </p>
      {% if user.is_authenticated and post_user.author == user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post_user.pk %}">
          редактировать запись
        </a>
      {% endif %}
      {% include 'posts/includes/comments.html' %}
    </article>
    
  </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author.username }}{% endblock %}
{% block content %}
{% load thumbnail %}
  <div class="container py-5">
    <div class="mb-5">   
      <h1>Все посты пользователя {{ author.get_full_name }}</h1>
      <h3>Всего постов: {{ page_obj.paginator.count }}</h3>
      {% if user.is_authenticated and author.username != user.username %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %}
    </div>
    {% for post in page_obj %}   
      <article>
        <ul>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %} 
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
      </article>
      {% if post.group.slug %}       
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}        
      {% if not forloop.last %}<hr>{% endif %}
      <!-- Остальные посты. после последнего нет черты -->
      <!-- Здесь подключён паджинатор --> 
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}  
  </div>
{% endblock %}